# -*- coding: utf-8 -*-
"""Tarea_02_binario.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YXG7QEMJpINfKCXKBzF0R9J1zP6nIDnu
"""

lista=[]
binario = []

numero = 47
numeroini=47
numero2 = numero
while numero2 != 0:
    modulo = numero2 % 2
    binario.append(numero2 % 2 )
    numero2= numero // 2
    numero = numero2
    lista.append(modulo)
    print(numero2)
    
    


residuo = numero%2

print("%d convertido a binario es :"%(numeroini))

lista = binario[::-1]


cantidad = int(len(lista))

adicion=0

while cantidad < 8:
    cantidad += 1
    binario.append(adicion)

lista = binario[::-1]
print(lista)